# Generated by Django 4.0.5 on 2022-06-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vendor',
            field=models.BooleanField(default=False),
        ),
    ]
