# Generated by Django 4.0.5 on 2022-06-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvapp', '0002_user_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=225, null=True, unique=True, verbose_name='emil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
