# Generated by Django 4.0.5 on 2022-06-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvapp', '0003_alter_user_email_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=225, null=True, unique=True, verbose_name='email'),
        ),
    ]
