# Generated by Django 4.0.5 on 2022-06-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvapp', '0005_user_shop_name_user_shop_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=225),
        ),
    ]
