# Generated by Django 4.0.5 on 2022-08-16 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kvapp', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shop_name',
            field=models.CharField(blank=True, default='#', max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='shop_url',
            field=models.URLField(blank=True, default='#', max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='UserLoginCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=225)),
                ('date', models.CharField(blank=True, max_length=225, null=True)),
                ('expiration', models.CharField(blank=True, max_length=225, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
