# Generated by Django 4.0.5 on 2022-08-16 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=225)),
                ('last_name', models.CharField(max_length=225)),
                ('company_name', models.CharField(blank=True, max_length=300, null=True)),
                ('country', models.CharField(max_length=225)),
                ('street_address1', models.TextField()),
                ('street_address2', models.TextField(blank=True, null=True)),
                ('town_city', models.CharField(max_length=225)),
                ('state', models.CharField(max_length=225)),
                ('postcode_zip', models.CharField(max_length=225)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=225)),
                ('last_name', models.CharField(max_length=225)),
                ('company_name', models.CharField(blank=True, max_length=300, null=True)),
                ('country', models.CharField(max_length=225)),
                ('street_address1', models.TextField()),
                ('street_address2', models.TextField(blank=True, null=True)),
                ('town_city', models.CharField(max_length=225)),
                ('state', models.CharField(max_length=225)),
                ('postcode_zip', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
