# Generated by Django 4.0.5 on 2022-08-13 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Customers', '0001_initial'),
        ('products', '0010_accessories_beauty_brand_clothing_face_and_body_kids_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10000000)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_customer', to=settings.AUTH_USER_MODEL)),
                ('customer_billing_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customers.billingaddress')),
                ('customer_shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customers.shippingaddress')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('product_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_vendor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
