# Generated by Django 4.0.5 on 2022-08-13 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='customer_billing_address',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='customer_shipping_address',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='product_vendor',
        ),
    ]
