# Generated by Django 4.0.5 on 2022-08-13 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0011_alter_product_price'),
        ('orders', '0002_remove_ordermodel_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='customer_billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Customers.billingaddress'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='customer_shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Customers.shippingaddress'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='product_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10000000, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='product_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_vendor', to=settings.AUTH_USER_MODEL),
        ),
    ]
