# Generated by Django 4.0.5 on 2022-08-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ordermodel_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='ipn_valid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
