# Generated by Django 4.0.5 on 2022-08-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_ordermodel_ipn_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
