# Generated by Django 4.0.5 on 2022-08-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_ordermodel_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
    ]
