# Generated by Django 4.0.5 on 2022-08-16 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory_name', models.CharField(max_length=225)),
                ('gender', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='beauty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_product_name', models.CharField(max_length=225)),
                ('gender', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=225)),
                ('gender', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_name', models.CharField(max_length=225)),
                ('gender', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='face_and_body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('gender', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='kids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=225)),
                ('gender', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe_type', models.CharField(max_length=225)),
                ('gender', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_name', models.CharField(max_length=225)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.IntegerField(default=0)),
                ('discounted_price', models.IntegerField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image1', models.FileField(blank=True, null=True, upload_to='product-image')),
                ('image2', models.FileField(blank=True, null=True, upload_to='product-image')),
                ('image3', models.FileField(blank=True, null=True, upload_to='product-image')),
                ('image4', models.FileField(blank=True, null=True, upload_to='product-image')),
                ('image5', models.FileField(blank=True, null=True, upload_to='product-image')),
                ('stock', models.IntegerField(default=0)),
                ('brand', models.CharField(blank=True, max_length=225, null=True)),
                ('color', models.CharField(blank=True, max_length=225, null=True)),
                ('size', models.CharField(blank=True, max_length=225, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('gender', models.CharField(blank=True, max_length=225, null=True)),
                ('weight', models.CharField(blank=True, max_length=225, null=True)),
                ('tags', models.CharField(blank=True, max_length=225, null=True)),
                ('purchase_note', models.TextField(blank=True, null=True)),
                ('visibility', models.CharField(blank=True, max_length=225, null=True)),
                ('collectors_pick', models.BooleanField(default=False)),
                ('product_reviews', models.BooleanField(default=True)),
                ('clicks', models.IntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.subcategory')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
