# Generated by Django 4.0.5 on 2022-06-30 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('stock', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=225)),
                ('size', models.CharField(blank=True, max_length=225, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('gender', models.CharField(blank=True, max_length=225, null=True)),
                ('weight', models.CharField(blank=True, max_length=225, null=True)),
                ('category1', models.CharField(max_length=225)),
                ('category2', models.CharField(max_length=225)),
                ('category3', models.CharField(blank=True, max_length=225, null=True)),
                ('category4', models.CharField(blank=True, max_length=225, null=True)),
                ('category5', models.CharField(blank=True, max_length=225, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
