# Generated by Django 4.0.5 on 2022-07-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to='product-image'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to='product-image'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to='product-image'),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.FileField(blank=True, null=True, upload_to='product-image'),
        ),
        migrations.AddField(
            model_name='product',
            name='image5',
            field=models.FileField(blank=True, null=True, upload_to='product-image'),
        ),
    ]
