# Generated by Django 4.0.5 on 2022-07-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_rename_category3_product_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
