# Generated by Django 4.0.5 on 2022-07-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_short_description_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='collectors_pick',
            field=models.BooleanField(default=False),
        ),
    ]
