# Generated by Django 4.0.5 on 2022-07-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_collectors_pick'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
