# Generated by Django 4.0.5 on 2022-08-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_accessories_beauty_brand_clothing_face_and_body_kids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10000000, null=True),
        ),
    ]
